//! Static contract checking for test and suite entries.
//!
//! The ordinary resolver/type checker owns expressions, ownership and
//! capability proofs.  This module consumes those proofs and closes the small
//! test-only boundary: hidden entries are `async? fn(): Unit ! E`, suite setup
//! cannot return, and the sealed `std.testing` operations have exact operand
//! shapes.  No runtime context is created here.

use std::collections::BTreeSet;
use std::error::Error;
use std::fmt;

use crate::test_plan::TestSourceClass;

pub const TEST_CHECK_FORMAT: &str = "tondo-test-check-draft/1";

/// The two kinds of hidden entries generated by test source checking.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum TestEntryKind {
    Test,
    SuiteSetup,
}

impl TestEntryKind {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Test => "test",
            Self::SuiteSetup => "suite-setup",
        }
    }
}

impl fmt::Display for TestEntryKind {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// The only normal results accepted by a hidden test entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NormalResult {
    Unit,
    Never,
    Other(String),
}

impl NormalResult {
    fn is_admitted(&self) -> bool {
        matches!(self, Self::Unit | Self::Never)
    }
}

/// Shape of an explicitly written return in a test body.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReturnShape {
    None,
    Bare,
    Value,
}

/// A nominal error participating in the closed inferred union `E`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct ErrorMember {
    name: String,
    discard: bool,
}

impl ErrorMember {
    pub fn new(name: impl Into<String>, discard: bool) -> Self {
        Self {
            name: name.into(),
            discard,
        }
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub const fn discard(&self) -> bool {
        self.discard
    }
}

/// Operand shapes recognized by the sealed `std.testing` surface.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum OperandShape {
    String,
    TagsMap,
    Bytes,
    Duration,
    VirtualTimeRef,
    Other(String),
}

/// Static facts for the callback passed to `withVirtualTime`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VirtualTimeClosureFacts {
    is_async: bool,
    send: bool,
    call_once: bool,
    returns_unit: bool,
    accepts_ref: bool,
    escapes_controller: bool,
    shares_controller: bool,
}

impl VirtualTimeClosureFacts {
    pub const fn new(
        is_async: bool,
        send: bool,
        call_once: bool,
        returns_unit: bool,
        accepts_ref: bool,
        escapes_controller: bool,
        shares_controller: bool,
    ) -> Self {
        Self {
            is_async,
            send,
            call_once,
            returns_unit,
            accepts_ref,
            escapes_controller,
            shares_controller,
        }
    }

    pub const fn valid(self) -> bool {
        self.is_async
            && self.send
            && self.call_once
            && self.returns_unit
            && self.accepts_ref
            && !self.escapes_controller
            && !self.shares_controller
    }

    pub const fn is_async(self) -> bool {
        self.is_async
    }

    pub const fn send(self) -> bool {
        self.send
    }

    pub const fn call_once(self) -> bool {
        self.call_once
    }

    pub const fn returns_unit(self) -> bool {
        self.returns_unit
    }

    pub const fn accepts_ref(self) -> bool {
        self.accepts_ref
    }

    pub const fn escapes_controller(self) -> bool {
        self.escapes_controller
    }

    pub const fn shares_controller(self) -> bool {
        self.shares_controller
    }
}

/// The closed operation vocabulary admitted by `std.testing`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TestOperation {
    Log {
        message: OperandShape,
    },
    Tags {
        values: OperandShape,
    },
    FailNow {
        message: OperandShape,
    },
    Skip {
        reason: OperandShape,
    },
    Attach {
        name: String,
        media_type: String,
        bytes: OperandShape,
    },
    Snapshot {
        name: String,
        actual: OperandShape,
    },
    WithVirtualTime(VirtualTimeClosureFacts),
    Settle,
    Advance {
        duration_ns: i128,
    },
}

impl TestOperation {
    pub fn log() -> Self {
        Self::Log {
            message: OperandShape::String,
        }
    }

    pub fn log_with(shape: OperandShape) -> Self {
        Self::Log { message: shape }
    }

    pub fn tags() -> Self {
        Self::Tags {
            values: OperandShape::TagsMap,
        }
    }

    pub fn tags_with(shape: OperandShape) -> Self {
        Self::Tags { values: shape }
    }

    pub fn fail_now() -> Self {
        Self::FailNow {
            message: OperandShape::String,
        }
    }

    pub fn skip() -> Self {
        Self::Skip {
            reason: OperandShape::String,
        }
    }

    pub fn attach(name: impl Into<String>, media_type: impl Into<String>) -> Self {
        Self::Attach {
            name: name.into(),
            media_type: media_type.into(),
            bytes: OperandShape::Bytes,
        }
    }

    pub fn attach_with_bytes(
        name: impl Into<String>,
        media_type: impl Into<String>,
        bytes: OperandShape,
    ) -> Self {
        Self::Attach {
            name: name.into(),
            media_type: media_type.into(),
            bytes,
        }
    }

    pub fn snapshot(name: impl Into<String>) -> Self {
        Self::Snapshot {
            name: name.into(),
            actual: OperandShape::String,
        }
    }

    pub fn snapshot_with_actual(name: impl Into<String>, actual: OperandShape) -> Self {
        Self::Snapshot {
            name: name.into(),
            actual,
        }
    }

    pub fn with_virtual_time(facts: VirtualTimeClosureFacts) -> Self {
        Self::WithVirtualTime(facts)
    }

    pub const fn settle() -> Self {
        Self::Settle
    }

    pub const fn advance(duration_ns: i128) -> Self {
        Self::Advance { duration_ns }
    }

    pub fn name(&self) -> Option<&str> {
        match self {
            Self::Attach { name, .. } | Self::Snapshot { name, .. } => Some(name),
            _ => None,
        }
    }

    pub const fn requires_async(&self) -> bool {
        matches!(
            self,
            Self::WithVirtualTime(_) | Self::Settle | Self::Advance { .. }
        )
    }
}

/// Proofs supplied by ordinary semantic checking.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct OrdinaryCheckFacts {
    violations: BTreeSet<OrdinaryViolation>,
    contains_await: bool,
    contains_scope: bool,
    contains_defer: bool,
    contains_unsafe: bool,
}

impl OrdinaryCheckFacts {
    pub fn valid() -> Self {
        Self::default()
    }

    pub fn with_violation(mut self, violation: OrdinaryViolation) -> Self {
        self.violations.insert(violation);
        self
    }

    pub const fn with_await(mut self) -> Self {
        self.contains_await = true;
        self
    }

    pub const fn with_scope(mut self) -> Self {
        self.contains_scope = true;
        self
    }

    pub const fn with_defer(mut self) -> Self {
        self.contains_defer = true;
        self
    }

    pub const fn with_unsafe(mut self) -> Self {
        self.contains_unsafe = true;
        self
    }

    pub fn violations(&self) -> impl ExactSizeIterator<Item = &OrdinaryViolation> {
        self.violations.iter()
    }

    pub const fn contains_await(&self) -> bool {
        self.contains_await
    }

    pub const fn contains_scope(&self) -> bool {
        self.contains_scope
    }

    pub const fn contains_defer(&self) -> bool {
        self.contains_defer
    }

    pub const fn contains_unsafe(&self) -> bool {
        self.contains_unsafe
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum OrdinaryViolation {
    Ownership,
    Borrow,
    Terminal,
    Send,
    Share,
    Unsafe,
}

impl OrdinaryViolation {
    pub const fn code(self) -> &'static str {
        match self {
            Self::Ownership => "E1401",
            Self::Borrow => "E1402",
            Self::Terminal => "E1403",
            Self::Send => "E1404",
            Self::Share => "E1405",
            Self::Unsafe => "E1701",
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Ownership => "ownership",
            Self::Borrow => "borrow",
            Self::Terminal => "terminal",
            Self::Send => "Send",
            Self::Share => "Share",
            Self::Unsafe => "unsafe",
        }
    }
}

/// Unchecked input to [`check`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TestBodyInput {
    node: String,
    source_class: TestSourceClass,
    kind: TestEntryKind,
    normal: NormalResult,
    return_shape: ReturnShape,
    errors: Vec<ErrorMember>,
    facts: OrdinaryCheckFacts,
    operations: Vec<TestOperation>,
}

impl TestBodyInput {
    pub fn new(node: impl Into<String>, kind: TestEntryKind) -> Self {
        Self {
            node: node.into(),
            source_class: TestSourceClass::UnitTest,
            kind,
            normal: NormalResult::Unit,
            return_shape: ReturnShape::None,
            errors: Vec::new(),
            facts: OrdinaryCheckFacts::valid(),
            operations: Vec::new(),
        }
    }

    pub fn with_source_class(mut self, source_class: TestSourceClass) -> Self {
        self.source_class = source_class;
        self
    }

    pub fn with_normal(mut self, normal: NormalResult) -> Self {
        self.normal = normal;
        self
    }

    pub const fn with_return(mut self, shape: ReturnShape) -> Self {
        self.return_shape = shape;
        self
    }

    pub fn with_errors(mut self, errors: impl IntoIterator<Item = ErrorMember>) -> Self {
        self.errors = errors.into_iter().collect();
        self
    }

    pub fn with_facts(mut self, facts: OrdinaryCheckFacts) -> Self {
        self.facts = facts;
        self
    }

    pub fn with_operations(mut self, operations: impl IntoIterator<Item = TestOperation>) -> Self {
        self.operations = operations.into_iter().collect();
        self
    }

    pub fn node(&self) -> &str {
        &self.node
    }

    pub fn source_class(&self) -> TestSourceClass {
        self.source_class
    }

    pub const fn kind(&self) -> TestEntryKind {
        self.kind
    }

    pub fn normal(&self) -> &NormalResult {
        &self.normal
    }

    pub const fn return_shape(&self) -> ReturnShape {
        self.return_shape
    }

    pub fn errors(&self) -> &[ErrorMember] {
        &self.errors
    }

    pub fn facts(&self) -> &OrdinaryCheckFacts {
        &self.facts
    }

    pub fn operations(&self) -> &[TestOperation] {
        &self.operations
    }
}

/// A checked hidden entry ready for HIR/lowering.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TestBodyContract {
    node: String,
    kind: TestEntryKind,
    is_async: bool,
    normal: NormalResult,
    errors: Vec<ErrorMember>,
    operations: Vec<TestOperation>,
    contains_scope: bool,
    contains_defer: bool,
    contains_unsafe: bool,
}

impl TestBodyContract {
    pub fn node(&self) -> &str {
        &self.node
    }

    pub const fn kind(&self) -> TestEntryKind {
        self.kind
    }

    pub const fn is_async(&self) -> bool {
        self.is_async
    }

    pub fn normal(&self) -> &NormalResult {
        &self.normal
    }

    pub fn errors(&self) -> &[ErrorMember] {
        &self.errors
    }

    pub fn operations(&self) -> &[TestOperation] {
        &self.operations
    }

    pub const fn contains_scope(&self) -> bool {
        self.contains_scope
    }

    pub const fn contains_defer(&self) -> bool {
        self.contains_defer
    }

    pub const fn contains_unsafe(&self) -> bool {
        self.contains_unsafe
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CheckError {
    EmptyNode,
    ProductionTesting {
        operation: &'static str,
    },
    InvalidNormalResult {
        kind: TestEntryKind,
        actual: NormalResult,
    },
    TestReturnValue,
    SuiteReturn,
    DuplicateError(String),
    NonDiscardError(String),
    OrdinaryViolation(OrdinaryViolation),
    InvalidOperand {
        operation: &'static str,
        expected: &'static str,
        actual: OperandShape,
    },
    InvalidName {
        operation: &'static str,
        name: String,
    },
    InvalidMediaType(String),
    VirtualTimeClosure,
    VirtualTimeNegativeDuration,
    VirtualTimeOverflow,
}

impl CheckError {
    pub const fn code(&self) -> &'static str {
        match self {
            Self::EmptyNode => "E2000",
            Self::ProductionTesting { .. } => "E2003",
            Self::InvalidNormalResult { .. } => "E1201",
            Self::TestReturnValue => "E1204",
            Self::SuiteReturn => "E1205",
            Self::DuplicateError(_) | Self::NonDiscardError(_) => "E1206",
            Self::OrdinaryViolation(violation) => violation.code(),
            Self::InvalidOperand { .. } => "E1210",
            Self::InvalidName { .. } => "P2006",
            Self::InvalidMediaType(_) => "P2006",
            Self::VirtualTimeClosure => "E1211",
            Self::VirtualTimeNegativeDuration => "P2005",
            Self::VirtualTimeOverflow => "P2005",
        }
    }
}

impl fmt::Display for CheckError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptyNode => formatter.write_str("test entry has an empty identity"),
            Self::ProductionTesting { operation } => write!(
                formatter,
                "{operation} belongs to test-only std.testing and cannot cross into production"
            ),
            Self::InvalidNormalResult { kind, actual } => {
                write!(formatter, "{kind} entry must return Unit or Never, got {actual:?}")
            }
            Self::TestReturnValue => formatter.write_str("a test entry cannot return a value"),
            Self::SuiteReturn => formatter.write_str("suite setup cannot use return"),
            Self::DuplicateError(name) => write!(formatter, "inferred error `{name}` is duplicated"),
            Self::NonDiscardError(name) => {
                write!(formatter, "inferred error `{name}` does not satisfy Discard")
            }
            Self::OrdinaryViolation(violation) => write!(
                formatter,
                "ordinary semantic check failed for {}",
                violation.as_str()
            ),
            Self::InvalidOperand {
                operation,
                expected,
                actual,
            } => write!(
                formatter,
                "{operation} expects {expected}, got {actual:?}"
            ),
            Self::InvalidName { operation, name } => {
                write!(formatter, "{operation} name `{name}` is invalid")
            }
            Self::InvalidMediaType(value) => {
                write!(formatter, "attachment media type `{value}` is invalid")
            }
            Self::VirtualTimeClosure => formatter.write_str(
                "withVirtualTime requires Send + CallOnce + fn(ref VirtualTime): Unit ! E suspends without escape or Share",
            ),
            Self::VirtualTimeNegativeDuration => {
                formatter.write_str("virtual time duration cannot be negative")
            }
            Self::VirtualTimeOverflow => formatter.write_str("virtual time duration overflows its domain"),
        }
    }
}

impl Error for CheckError {}

/// Check one hidden test or suite-setup entry.
pub fn check(input: TestBodyInput) -> Result<TestBodyContract, CheckError> {
    if input.node.is_empty() {
        return Err(CheckError::EmptyNode);
    }
    if input.source_class == TestSourceClass::Production
        && let Some(operation) = input.operations.first()
    {
        return Err(CheckError::ProductionTesting {
            operation: operation_name(operation),
        });
    }
    if !input.normal.is_admitted() {
        return Err(CheckError::InvalidNormalResult {
            kind: input.kind,
            actual: input.normal,
        });
    }
    match (input.kind, input.return_shape) {
        (TestEntryKind::SuiteSetup, ReturnShape::None)
        | (TestEntryKind::Test, ReturnShape::None) => {}
        (TestEntryKind::SuiteSetup, _) => return Err(CheckError::SuiteReturn),
        (TestEntryKind::Test, ReturnShape::Value) => return Err(CheckError::TestReturnValue),
        (TestEntryKind::Test, ReturnShape::Bare) => {}
    }
    let errors = normalize_errors(&input.errors)?;
    if let Some(violation) = input.facts.violations().next().copied() {
        return Err(CheckError::OrdinaryViolation(violation));
    }

    let mut operations = input.operations;
    let mut is_async = input.facts.contains_await;
    let mut seen_attachments = BTreeSet::new();
    let mut seen_snapshots = BTreeSet::new();
    for operation in &operations {
        if operation.requires_async() {
            is_async = true;
        }
        validate_operation(operation, &mut seen_attachments, &mut seen_snapshots)?;
    }
    operations.shrink_to_fit();
    Ok(TestBodyContract {
        node: input.node,
        kind: input.kind,
        is_async,
        normal: input.normal,
        errors,
        operations,
        contains_scope: input.facts.contains_scope,
        contains_defer: input.facts.contains_defer,
        contains_unsafe: input.facts.contains_unsafe,
    })
}

fn normalize_errors(errors: &[ErrorMember]) -> Result<Vec<ErrorMember>, CheckError> {
    let mut output = errors.to_vec();
    output.sort();
    let mut seen = BTreeSet::new();
    for error in &output {
        if !seen.insert(error.name.clone()) {
            return Err(CheckError::DuplicateError(error.name.clone()));
        }
        if !error.discard {
            return Err(CheckError::NonDiscardError(error.name.clone()));
        }
    }
    Ok(output)
}

fn validate_operation(
    operation: &TestOperation,
    seen_attachments: &mut BTreeSet<String>,
    seen_snapshots: &mut BTreeSet<String>,
) -> Result<(), CheckError> {
    match operation {
        TestOperation::Log { message }
        | TestOperation::FailNow { message }
        | TestOperation::Skip { reason: message } => {
            let operation_name = match operation {
                TestOperation::Log { .. } => "log",
                TestOperation::FailNow { .. } => "failNow",
                TestOperation::Skip { .. } => "skip",
                _ => unreachable!(),
            };
            require_operand(operation_name, "String", message, OperandShape::String)?;
        }
        TestOperation::Tags { values } => {
            require_operand("tags", "Map[String, String]", values, OperandShape::TagsMap)?;
        }
        TestOperation::Attach {
            name,
            media_type,
            bytes,
        } => {
            validate_name("attach", name)?;
            if !seen_attachments.insert(name.clone()) {
                return Err(CheckError::InvalidName {
                    operation: "attach duplicate",
                    name: name.clone(),
                });
            }
            validate_media_type(media_type)?;
            require_operand("attach", "bytes.Bytes", bytes, OperandShape::Bytes)?;
        }
        TestOperation::Snapshot { name, actual } => {
            validate_name("snapshot", name)?;
            if !seen_snapshots.insert(name.clone()) {
                return Err(CheckError::InvalidName {
                    operation: "snapshot duplicate",
                    name: name.clone(),
                });
            }
            require_operand("snapshot", "String", actual, OperandShape::String)?;
        }
        TestOperation::WithVirtualTime(facts) => {
            if !facts.valid() {
                return Err(CheckError::VirtualTimeClosure);
            }
        }
        TestOperation::Settle => {}
        TestOperation::Advance { duration_ns } => {
            if *duration_ns < 0 {
                return Err(CheckError::VirtualTimeNegativeDuration);
            }
            if *duration_ns > i64::MAX as i128 {
                return Err(CheckError::VirtualTimeOverflow);
            }
        }
    }
    Ok(())
}

fn require_operand(
    operation: &'static str,
    expected: &'static str,
    actual: &OperandShape,
    expected_shape: OperandShape,
) -> Result<(), CheckError> {
    if actual != &expected_shape {
        return Err(CheckError::InvalidOperand {
            operation,
            expected,
            actual: actual.clone(),
        });
    }
    Ok(())
}

fn validate_name(operation: &'static str, value: &str) -> Result<(), CheckError> {
    if value.is_empty()
        || value.len() > 128
        || value.contains(['/', '\\', '\n', '\r'])
        || value == "."
        || value == ".."
    {
        return Err(CheckError::InvalidName {
            operation,
            name: value.to_owned(),
        });
    }
    Ok(())
}

fn validate_media_type(value: &str) -> Result<(), CheckError> {
    if value.is_empty()
        || value.len() > 127
        || value.contains([' ', '\t', '\n', '\r'])
        || value.matches('/').count() != 1
        || value.starts_with('/')
        || value.ends_with('/')
    {
        return Err(CheckError::InvalidMediaType(value.to_owned()));
    }
    Ok(())
}

fn operation_name(operation: &TestOperation) -> &'static str {
    match operation {
        TestOperation::Log { .. } => "log",
        TestOperation::Tags { .. } => "tags",
        TestOperation::FailNow { .. } => "failNow",
        TestOperation::Skip { .. } => "skip",
        TestOperation::Attach { .. } => "attach",
        TestOperation::Snapshot { .. } => "snapshot",
        TestOperation::WithVirtualTime(_) => "withVirtualTime",
        TestOperation::Settle => "settle",
        TestOperation::Advance { .. } => "advance",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test(node: &str) -> TestBodyInput {
        TestBodyInput::new(node, TestEntryKind::Test)
    }

    fn setup(node: &str) -> TestBodyInput {
        TestBodyInput::new(node, TestEntryKind::SuiteSetup)
    }

    fn virtual_time() -> VirtualTimeClosureFacts {
        VirtualTimeClosureFacts::new(true, true, true, true, true, false, false)
    }

    #[test]
    fn admits_unit_never_and_infers_async_from_ordinary_or_temporal_operations() {
        let contract = check(
            test("math::adds")
                .with_facts(
                    OrdinaryCheckFacts::valid()
                        .with_await()
                        .with_scope()
                        .with_defer(),
                )
                .with_operations([
                    TestOperation::log(),
                    TestOperation::with_virtual_time(virtual_time()),
                    TestOperation::settle(),
                    TestOperation::advance(10),
                ])
                .with_errors([
                    ErrorMember::new("IoError", true),
                    ErrorMember::new("ParseError", true),
                ]),
        )
        .unwrap();
        assert!(contract.is_async());
        assert_eq!(contract.normal(), &NormalResult::Unit);
        assert_eq!(contract.errors()[0].name(), "IoError");
        assert!(contract.contains_scope());
        assert!(contract.contains_defer());
        assert!(!contract.contains_unsafe());
        assert_eq!(contract.operations().len(), 4);
        let never = check(test("never").with_normal(NormalResult::Never)).unwrap();
        assert_eq!(never.normal(), &NormalResult::Never);
    }

    #[test]
    fn setup_cannot_return_but_test_allows_bare_return() {
        assert!(matches!(
            check(setup("suite::setup").with_return(ReturnShape::Bare)),
            Err(CheckError::SuiteReturn)
        ));
        assert!(matches!(
            check(test("test").with_return(ReturnShape::Value)),
            Err(CheckError::TestReturnValue)
        ));
        assert!(check(test("test").with_return(ReturnShape::Bare)).is_ok());
        assert!(check(setup("suite")).is_ok());
    }

    #[test]
    fn rejects_empty_or_non_unit_normal_results() {
        assert!(matches!(
            check(TestBodyInput::new("", TestEntryKind::Test)),
            Err(CheckError::EmptyNode)
        ));
        assert!(matches!(
            check(test("bad").with_normal(NormalResult::Other("Int".into()))),
            Err(CheckError::InvalidNormalResult { .. })
        ));
    }

    #[test]
    fn errors_are_closed_discarded_sorted_and_unique() {
        let contract = check(test("errors").with_errors([
            ErrorMember::new("ZError", true),
            ErrorMember::new("AError", true),
        ]))
        .unwrap();
        assert_eq!(
            contract
                .errors()
                .iter()
                .map(ErrorMember::name)
                .collect::<Vec<_>>(),
            vec!["AError", "ZError"]
        );
        assert!(matches!(
            check(
                test("duplicate")
                    .with_errors([ErrorMember::new("E", true), ErrorMember::new("E", true),])
            ),
            Err(CheckError::DuplicateError(_))
        ));
        assert!(matches!(
            check(test("affine").with_errors([ErrorMember::new("Affine", false)])),
            Err(CheckError::NonDiscardError(_))
        ));
    }

    #[test]
    fn ordinary_semantic_violations_are_not_relaxed_for_tests() {
        for violation in [
            OrdinaryViolation::Ownership,
            OrdinaryViolation::Borrow,
            OrdinaryViolation::Terminal,
            OrdinaryViolation::Send,
            OrdinaryViolation::Share,
            OrdinaryViolation::Unsafe,
        ] {
            let error = check(
                test("ordinary").with_facts(OrdinaryCheckFacts::valid().with_violation(violation)),
            )
            .unwrap_err();
            assert!(matches!(error, CheckError::OrdinaryViolation(value) if value == violation));
            assert_eq!(error.code(), violation.code());
        }
    }

    #[test]
    fn all_control_and_metadata_operations_have_exact_shapes() {
        let valid = [
            TestOperation::log(),
            TestOperation::tags(),
            TestOperation::fail_now(),
            TestOperation::skip(),
            TestOperation::attach("report", "text/plain"),
            TestOperation::snapshot("golden"),
        ];
        assert!(check(test("operations").with_operations(valid)).is_ok());
        for operation in [
            TestOperation::log_with(OperandShape::Other("Bytes".into())),
            TestOperation::tags_with(OperandShape::Other("Array".into())),
            TestOperation::attach_with_bytes("report", "text/plain", OperandShape::String),
            TestOperation::snapshot_with_actual("golden", OperandShape::Bytes),
        ] {
            assert!(matches!(
                check(test("bad-operation").with_operations([operation])),
                Err(CheckError::InvalidOperand { .. })
            ));
        }
    }

    #[test]
    fn attachment_snapshot_names_and_media_types_are_closed() {
        for operation in [
            TestOperation::attach("", "text/plain"),
            TestOperation::attach("../secret", "text/plain"),
            TestOperation::attach("x", "textplain"),
            TestOperation::attach("x", "text/ plain"),
        ] {
            assert!(matches!(
                check(test("invalid").with_operations([operation])),
                Err(CheckError::InvalidName { .. }) | Err(CheckError::InvalidMediaType(_))
            ));
        }
        assert!(matches!(
            check(test("duplicate").with_operations([
                TestOperation::attach("x", "text/plain"),
                TestOperation::attach("x", "text/plain"),
            ])),
            Err(CheckError::InvalidName { .. })
        ));
        assert!(matches!(
            check(
                test("duplicate")
                    .with_operations([TestOperation::snapshot("x"), TestOperation::snapshot("x"),])
            ),
            Err(CheckError::InvalidName { .. })
        ));
    }

    #[test]
    fn virtual_time_requires_closed_callback_and_nonnegative_finite_duration() {
        assert!(
            check(test("time").with_operations([TestOperation::with_virtual_time(virtual_time())]))
                .is_ok()
        );
        let invalids = [
            VirtualTimeClosureFacts::new(false, true, true, true, true, false, false),
            VirtualTimeClosureFacts::new(true, false, true, true, true, false, false),
            VirtualTimeClosureFacts::new(true, true, false, true, true, false, false),
            VirtualTimeClosureFacts::new(true, true, true, false, true, false, false),
            VirtualTimeClosureFacts::new(true, true, true, true, false, false, false),
            VirtualTimeClosureFacts::new(true, true, true, true, true, true, false),
            VirtualTimeClosureFacts::new(true, true, true, true, true, false, true),
        ];
        for facts in invalids {
            assert!(matches!(
                check(test("time").with_operations([TestOperation::with_virtual_time(facts)])),
                Err(CheckError::VirtualTimeClosure)
            ));
        }
        assert!(matches!(
            check(test("time").with_operations([TestOperation::advance(-1)])),
            Err(CheckError::VirtualTimeNegativeDuration)
        ));
        assert!(matches!(
            check(test("time").with_operations([TestOperation::advance(i64::MAX as i128 + 1)])),
            Err(CheckError::VirtualTimeOverflow)
        ));
    }

    #[test]
    fn test_only_operations_are_rejected_in_production() {
        for operation in [
            TestOperation::log(),
            TestOperation::tags(),
            TestOperation::fail_now(),
            TestOperation::skip(),
            TestOperation::attach("x", "text/plain"),
            TestOperation::snapshot("x"),
            TestOperation::with_virtual_time(virtual_time()),
            TestOperation::settle(),
            TestOperation::advance(0),
        ] {
            let error = check(
                test("production")
                    .with_source_class(TestSourceClass::Production)
                    .with_operations([operation]),
            )
            .unwrap_err();
            assert_eq!(error.code(), "E2003");
        }
    }

    #[test]
    fn accessors_and_display_vocabulary_are_closed() {
        let facts = OrdinaryCheckFacts::valid()
            .with_await()
            .with_scope()
            .with_defer()
            .with_unsafe();
        assert!(facts.contains_await());
        assert!(facts.contains_scope());
        assert!(facts.contains_defer());
        assert!(facts.contains_unsafe());
        let time = virtual_time();
        assert!(time.is_async() && time.send() && time.call_once() && time.returns_unit());
        assert!(time.accepts_ref() && !time.escapes_controller() && !time.shares_controller());
        assert_eq!(TestEntryKind::Test.to_string(), "test");
        assert_eq!(TestEntryKind::SuiteSetup.to_string(), "suite-setup");
        assert_eq!(TEST_CHECK_FORMAT, "tondo-test-check-draft/1");
        for error in [
            CheckError::EmptyNode,
            CheckError::ProductionTesting { operation: "log" },
            CheckError::InvalidNormalResult {
                kind: TestEntryKind::Test,
                actual: NormalResult::Other("T".into()),
            },
            CheckError::TestReturnValue,
            CheckError::SuiteReturn,
            CheckError::DuplicateError("E".into()),
            CheckError::NonDiscardError("E".into()),
            CheckError::InvalidOperand {
                operation: "log",
                expected: "String",
                actual: OperandShape::Bytes,
            },
            CheckError::InvalidName {
                operation: "attach",
                name: "x".into(),
            },
            CheckError::InvalidMediaType("bad".into()),
            CheckError::VirtualTimeClosure,
            CheckError::VirtualTimeNegativeDuration,
            CheckError::VirtualTimeOverflow,
        ] {
            assert!(!error.to_string().is_empty());
            assert!(!error.code().is_empty());
        }
    }
}
