[package]
name = "tondo-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
conformance = []

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tondo-stdlib = { path = "../tondo-stdlib" }
tondo-vm = { path = "../tondo-vm" }
unicode-ident.workspace = true
unicode-normalization.workspace = true
unicode-security.workspace = true
os_pipe.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"
