#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

evidence="${TONDO_STDLIB_OWNER_EVIDENCE:-testing/stdlib-owner-evidence.json}"

die() {
    echo "stdlib owner evidence: $*" >&2
    exit 1
}

[[ -f "$evidence" ]] || die "missing evidence registry: $evidence"
tail -c 1 "$evidence" | cmp -s <(printf '\n') || die "evidence registry must end with LF"
! grep -nE $'\r|[[:blank:]]$' "$evidence" >/dev/null || die "evidence registry contains CR or trailing whitespace"

jq -e '
  .format == "tondo-stdlib-owner-evidence/1"
  and .edition == "0.1"
  and .phase == "STD-0.1A"
  and .status == "draft-evidence"
  and (.leaves | type == "array" and length > 0)
  and ([.leaves[].id] | unique | length) == (.leaves | length)
  and all(.leaves[];
    (.id | type == "string" and startswith("STD-A-"))
    and (.contract | type == "string" and endswith(".json"))
    and (.owners | type == "array" and length > 0 and (unique | length) == length)
  )
  and ([.owners[].id] | unique | length) == (.owners | length)
  and all(.owners[];
    (.id | type == "string" and test("^std\\.[a-z]+$"))
    and (.layer | test("^A[0-4]$"))
    and ((.cells | keys_unsorted) | sort) == ["CONF", "DOC", "FUZZ", "HOST", "IMPL", "MODEL", "PERF", "SPEC", "TEST"]
    and all(.cells[];
      (.status | ["verified", "partial", "pending", "not-applicable", "gap"] | index(.)) != null
      and (.refs | type == "array" and length > 0 and all(.[]; type == "string" and length > 0))
      and (if .status == "verified" then .reason == null else (.reason | type == "string" and length > 0) end)
    )
    and (.budgets | type == "object" and length > 0)
    and all(.budgets[];
      (.unit | type == "string" and length > 0)
      and .direction == "lower-is-better"
      and (.max_regression_basis_points | type == "number" and . >= 0)
      and (.state | type == "string" and length > 0)
    )
    and (.commands | type == "array" and length > 0 and all(.[]; type == "string" and length > 0))
  )
  and ([.leaves[].owners[]] | sort) == ([.owners[].id] | sort)
  and (any(.leaves[]; .id == "STD-A-META-EVIDENCE-001" and .owners == ["std.meta"]))
  and (any(.leaves[]; .id == "STD-A-REFLECT-EVIDENCE-001" and .owners == ["std.reflect"]))
  and (any(.leaves[]; .id == "STD-A-BYTES-EVIDENCE-001" and .owners == ["std.bytes"]))
  and (any(.leaves[]; .id == "STD-A-CORE-EVIDENCE-001" and .owners == ["std.core"]))
  and (any(.leaves[]; .id == "STD-A-TEXT-EVIDENCE-001" and .owners == ["std.text"]))
  and (any(.leaves[]; .id == "STD-A-COLL-EVIDENCE-001" and .owners == ["std.collections"]))
  and (any(.leaves[]; .id == "STD-A-ITER-EVIDENCE-001" and .owners == ["std.iter"]))
  and (any(.leaves[]; .id == "STD-A-MATH-EVIDENCE-001" and .owners == ["std.math"]))
  and (any(.leaves[]; .id == "STD-A-FMT-EVIDENCE-001" and .owners == ["std.format"]))
  and (any(.leaves[]; .id == "STD-A-IO-EVIDENCE-001" and .owners == ["std.io"]))
  and (any(.leaves[]; .id == "STD-A-ASYNC-API-001" and .owners == ["std.async"]))
  and (any(.leaves[]; .id == "STD-A-PATH-EVIDENCE-001" and .owners == ["std.path"]))
  and (any(.leaves[]; .id == "STD-A-CONSOLE-EVIDENCE-001" and .owners == ["std.console"]))
  and (any(.leaves[]; .id == "STD-A-FS-EVIDENCE-001" and .owners == ["std.fs"]))
  and (any(.leaves[]; .id == "STD-A-PROC-EVIDENCE-001" and .owners == ["std.process"]))
  and (any(.leaves[]; .id == "STD-A-SER-EVIDENCE-001" and .owners == ["std.serialization"]))
  and (any(.leaves[]; .id == "STD-A-JSON-EVIDENCE-001" and .owners == ["std.json"]))
  and (any(.leaves[]; .id == "STD-A-MSGPACK-EVIDENCE-001" and .owners == ["std.messagepack"]))
  and (any(.leaves[]; .id == "STD-A-PROTOBUF-EVIDENCE-001" and .owners == ["std.protobuf"]))
  and (any(.leaves[]; .id == "STD-A-TESTING-EVIDENCE-001" and .owners == ["std.testing"]))
  and (any(.leaves[]; .id == "STD-A-TIME-EVIDENCE-001" and .owners == ["std.time"]))
  and (any(.leaves[]; .id == "STD-A-ENV-EVIDENCE-001" and .owners == ["std.env"]))
  and (.owners[] | select(.id == "std.meta") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.meta") | .cells.HOST.reason | contains("build-only"))
  and (.owners[] | select(.id == "std.meta") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.meta") | .cells.PERF.reason | contains("baseline"))
  and (.owners[] | select(.id == "std.reflect") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.reflect") | .cells.HOST.reason | contains("metadata-only"))
  and (.owners[] | select(.id == "std.reflect") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.bytes") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.bytes") | .cells.HOST.reason | contains("intrinsic"))
  and (.owners[] | select(.id == "std.bytes") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.core") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.core") | .cells.HOST.reason | contains("intrinsic"))
  and (.owners[] | select(.id == "std.core") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.core") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.core") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.core") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.core") | .cells.PERF.reason | contains("owner-specific"))
  and (.owners[] | select(.id == "std.text") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.text") | .cells.HOST.reason | contains("intrinsic"))
  and (.owners[] | select(.id == "std.text") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.text") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.text") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.text") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.text") | .cells.PERF.reason | contains("owner-specific"))
  and (.owners[] | select(.id == "std.collections") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.collections") | .cells.HOST.reason | contains("intrinsic"))
  and (.owners[] | select(.id == "std.collections") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.collections") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.collections") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.collections") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.collections") | .cells.PERF.reason | contains("owner-specific"))
  and (.owners[] | select(.id == "std.iter") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.iter") | .cells.HOST.reason | contains("intrinsic"))
  and (.owners[] | select(.id == "std.iter") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.iter") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.iter") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.iter") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.iter") | .cells.PERF.reason | contains("owner-specific"))
  and (.owners[] | select(.id == "std.math") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.math") | .cells.HOST.reason | contains("intrinsic"))
  and (.owners[] | select(.id == "std.math") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.math") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.math") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.math") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.math") | .cells.PERF.reason | contains("owner-specific"))
  and (.owners[] | select(.id == "std.format") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.format") | .cells.HOST.reason | contains("intrinsic"))
  and (.owners[] | select(.id == "std.format") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.format") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.format") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.format") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.format") | .cells.PERF.reason | contains("owner-specific"))
  and (.owners[] | select(.id == "std.format") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.format") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.io") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.io") | .cells.HOST.reason | contains("portable"))
  and (.owners[] | select(.id == "std.io") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.io") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.io") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.io") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.io") | .cells.PERF.reason | contains("owner-specific"))
  and (.owners[] | select(.id == "std.io") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.io") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.async") | .cells.SPEC.status == "verified")
  and (.owners[] | select(.id == "std.async") | .cells.IMPL.status == "partial")
  and (.owners[] | select(.id == "std.async") | .cells.IMPL.reason | contains("generic async-iterator"))
  and (.owners[] | select(.id == "std.async") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.async") | .cells.HOST.reason | contains("intrinsic"))
  and (.owners[] | select(.id == "std.async") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.async") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.async") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.async") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.async") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.async") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.path") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.path") | .cells.HOST.reason | contains("purely lexical"))
  and (.owners[] | select(.id == "std.path") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.path") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.path") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.path") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.path") | .cells.PERF.reason | contains("owner-specific"))
  and (.owners[] | select(.id == "std.path") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.path") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.console") | .cells.HOST.status == "verified")
  and (.owners[] | select(.id == "std.console") | .cells.HOST.reason == null)
  and (.owners[] | select(.id == "std.console") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.console") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.console") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.console") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.console") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.console") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.fs") | .cells.SPEC.status == "verified")
  and (.owners[] | select(.id == "std.fs") | .cells.IMPL.status == "verified")
  and (.owners[] | select(.id == "std.fs") | .cells.HOST.status == "verified")
  and (.owners[] | select(.id == "std.fs") | .cells.HOST.reason == null)
  and (.owners[] | select(.id == "std.fs") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.fs") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.fs") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.fs") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.fs") | .cells.PERF.reason | contains("target-specific"))
  and (.owners[] | select(.id == "std.fs") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.fs") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.process") | .cells.SPEC.status == "verified")
  and (.owners[] | select(.id == "std.process") | .cells.IMPL.status == "verified")
  and (.owners[] | select(.id == "std.process") | .cells.HOST.status == "verified")
  and (.owners[] | select(.id == "std.process") | .cells.HOST.reason == null)
  and (.owners[] | select(.id == "std.process") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.process") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.process") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.process") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.process") | .cells.PERF.reason | contains("target-specific"))
  and (.owners[] | select(.id == "std.process") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.process") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.serialization") | .cells.SPEC.status == "verified")
  and (.owners[] | select(.id == "std.serialization") | .cells.IMPL.status == "verified")
  and (.owners[] | select(.id == "std.serialization") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.serialization") | .cells.HOST.reason | contains("portable"))
  and (.owners[] | select(.id == "std.serialization") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.serialization") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.serialization") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.serialization") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.serialization") | .cells.PERF.reason | contains("baselines"))
  and (.owners[] | select(.id == "std.serialization") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.serialization") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.json") | .cells.SPEC.status == "verified")
  and (.owners[] | select(.id == "std.json") | .cells.IMPL.status == "verified")
  and (.owners[] | select(.id == "std.json") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.json") | .cells.HOST.reason | contains("portable"))
  and (.owners[] | select(.id == "std.json") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.json") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.json") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.json") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.json") | .cells.PERF.reason | contains("baselines"))
  and (.owners[] | select(.id == "std.json") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.json") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.messagepack") | .cells.SPEC.status == "verified")
  and (.owners[] | select(.id == "std.messagepack") | .cells.IMPL.status == "verified")
  and (.owners[] | select(.id == "std.messagepack") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.messagepack") | .cells.HOST.reason | contains("portable"))
  and (.owners[] | select(.id == "std.messagepack") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.messagepack") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.messagepack") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.messagepack") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.messagepack") | .cells.PERF.reason | contains("baselines"))
  and (.owners[] | select(.id == "std.messagepack") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.messagepack") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.protobuf") | .cells.SPEC.status == "verified")
  and (.owners[] | select(.id == "std.protobuf") | .cells.IMPL.status == "verified")
  and (.owners[] | select(.id == "std.protobuf") | .cells.HOST.status == "not-applicable")
  and (.owners[] | select(.id == "std.protobuf") | .cells.HOST.reason | contains("portable"))
  and (.owners[] | select(.id == "std.protobuf") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.protobuf") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.protobuf") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.protobuf") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.protobuf") | .cells.PERF.reason | contains("baselines"))
  and (.owners[] | select(.id == "std.protobuf") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.protobuf") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.testing") | .cells.SPEC.status == "verified")
  and (.owners[] | select(.id == "std.testing") | .cells.IMPL.status == "verified")
  and (.owners[] | select(.id == "std.testing") | .cells.HOST.status == "verified")
  and (.owners[] | select(.id == "std.testing") | .cells.HOST.reason == null)
  and (.owners[] | select(.id == "std.testing") | .cells.MODEL.status == "verified")
  and (.owners[] | select(.id == "std.testing") | .cells.TEST.status == "verified")
  and (.owners[] | select(.id == "std.testing") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.testing") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.testing") | .cells.PERF.reason | contains("baseline"))
  and (.owners[] | select(.id == "std.testing") | .cells.CONF.status == "partial")
  and (.owners[] | select(.id == "std.testing") | .cells.DOC.status == "verified")
  and (.owners[] | select(.id == "std.time") | .cells.HOST.status == "verified")
  and (.owners[] | select(.id == "std.time") | .cells.HOST.reason == null)
  and (.owners[] | select(.id == "std.time") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.time") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.time") | .cells.PERF.reason | contains("provider-scoped"))
  and (.owners[] | select(.id == "std.env") | .cells.HOST.status == "verified")
  and (.owners[] | select(.id == "std.env") | .cells.HOST.reason == null)
  and (.owners[] | select(.id == "std.env") | .cells.FUZZ.status == "partial")
  and (.owners[] | select(.id == "std.env") | .cells.PERF.status == "partial")
  and (.owners[] | select(.id == "std.env") | .cells.PERF.reason | contains("capability-scoped"))
' "$evidence" >/dev/null || die "invalid evidence registry"

while IFS=$'\t' read -r leaf contract owner; do
    [[ -f "$root/$contract" ]] || die "missing owner contract: $contract"
    jq -e --arg owner "$owner" '
      .format == "tondo-stdlib-owner-contract/1"
      and (
        .owner == $owner
        or ((.owners // []) | (type == "array" and (index($owner) != null)))
      )
      and (.test_matrix | type == "array" and length > 0)
    ' "$root/$contract" >/dev/null || die "owner contract does not match evidence leaf: $leaf"
done < <(jq -r '.leaves[] | . as $leaf | .owners[] | [$leaf.id, $leaf.contract, .] | @tsv' "$evidence")

while IFS= read -r ref; do
    base="${ref%%#*}"
    [[ -e "$root/$base" ]] || die "missing evidence reference: $ref"
done < <(jq -r '.owners[].cells[] | .refs[]' "$evidence")

while IFS= read -r command; do
    if [[ "$command" == scripts/* ]]; then
        [[ -x "$root/$command" ]] || die "evidence command is not executable: $command"
    fi
done < <(jq -r '.owners[].commands[]' "$evidence")

echo "stdlib owner evidence: OK (std.meta + std.reflect + std.bytes + std.core + std.text + std.collections + std.iter + std.math + std.format + std.io + std.path + std.console + std.fs + std.process + std.serialization + std.json + std.messagepack + std.protobuf + std.testing + std.time + std.env; nine cells explicit per owner)"
